---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on:
  #####################################
  # Start the job on all push to main #
  #####################################
  push:
    branches:
      # pushes to main will trigger an EDGE image
      - main

  ##############################################
  # Start the job on all pull requests to main #
  ##############################################
  pull_request:
    branches:
      - main

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Debug
          ACTIONS_RUNNER_DEBUG: false
          # Options
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yaml
          # Enabled validation
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_SHELL_SHFMT: true
          # Disabled validation
          # VALIDATE_ANSIBLE: false
          # VALIDATE_ARM: false
          # VALIDATE_CLANG_FORMAT: false
          # VALIDATE_CLOJURE: false
          # VALIDATE_CLOUDFORMATION: false
          # VALIDATE_COFFEESCRIPT: false
          # VALIDATE_CPP: false
          # VALIDATE_CSHARP: false
          # VALIDATE_CSS: false
          # VALIDATE_DART: false
          # VALIDATE_DOCKERFILE: true
          # VALIDATE_EDITORCONFIG: false
          # VALIDATE_ENV: false
          # VALIDATE_GHERKIN: false
          # VALIDATE_GO: false
          # VALIDATE_GOOGLE_JAVA_FORMAT: false
          # VALIDATE_GROOVY: false
          # VALIDATE_HTML: false
          # VALIDATE_JAVA: false
          # VALIDATE_JAVASCRIPT_ES: false
          # VALIDATE_JAVASCRIPT_STANDARD: false
          # VALIDATE_JSCPD: false
          # VALIDATE_JSON: false
          # VALIDATE_JSX: false
          # VALIDATE_KOTLIN: false
          # VALIDATE_KUBERNETES_KUBEVAL: false
          # VALIDATE_LATEX: false
          # VALIDATE_LUA: false
          # VALIDATE_MARKDOWN: false
          # VALIDATE_NATURAL_LANGUAGE: false
          # VALIDATE_OPENAPI: false
          # VALIDATE_PERL: false
          # VALIDATE_PHP_BUILTIN: false
          # VALIDATE_PHP_PHPCS: false
          # VALIDATE_PHP_PHPSTAN: false
          # VALIDATE_PHP_PSALM: false
          # VALIDATE_PHP: false
          # VALIDATE_POWERSHELL: false
          # VALIDATE_PROTOBUF: false
          # VALIDATE_PYTHON_BLACK: false
          # VALIDATE_PYTHON_FLAKE8: false
          # VALIDATE_PYTHON_ISORT: false
          # VALIDATE_PYTHON_MYPY: false
          # VALIDATE_PYTHON_PYLINT: false
          # VALIDATE_PYTHON: false
          # VALIDATE_R: false
          # VALIDATE_RAKU: false
          # VALIDATE_RUBY: false
          # VALIDATE_RUST_2015: false
          # VALIDATE_RUST_2018: false
          # VALIDATE_RUST_CLIPPY: false
          # VALIDATE_SCALAFMT_LINT: false
          # VALIDATE_SNAKEMAKE_LINT: false
          # VALIDATE_SNAKEMAKE_SNAKEFMT: false
          # VALIDATE_SQL: false
          # VALIDATE_SQLFLUFF: false
          # VALIDATE_STATES: false
          # VALIDATE_TEKTON: false
          # VALIDATE_TERRAFORM_TERRASCAN: false
          # VALIDATE_TERRAFORM_TFLINT: false
          # VALIDATE_TERRAGRUNT: false
          # VALIDATE_TSX: false
          # VALIDATE_TYPESCRIPT_ES: false
          # VALIDATE_TYPESCRIPT_STANDARD: false
          # VALIDATE_XML: false
          # VALIDATE_YAML: false
